name: "numix"
services:
  redis:
    image: redis:latest
    container_name: numix-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=America/Merida
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6380:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - numix_net
  postgres:
    image: postgres:16
    container_name: numix_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Merida
      PGTZ: America/Merida
    ports:
      - "54325:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - numix_net
  s3:
    image: minio/minio:latest
    container_name: numix_s3
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: America/Merida
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./s3/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - numix_net
  app:
    image: numix-app-tomcat
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: numix_app_tomcat
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      TOMCAT_MANAGER_USERNAME: ${TOMCAT_MANAGER_USERNAME:-cargo}
      TOMCAT_MANAGER_PASSWORD: ${TOMCAT_MANAGER_PASSWORD:-cargo123}
      TZ: America/Merida
    depends_on:
      - postgres
      - redis
      - s3
    networks:
      - numix_net
volumes: {}

networks:
  numix_net:
    name: numix_net
