spring.application.name=web
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
numix.i18n.default-locale=es
server.error.whitelabel.enabled=false
