spring.datasource.url=${NUMIX_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${NUMIX_DB_USERNAME}
spring.datasource.password=${NUMIX_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
